vscode:
  extensions:
    - toba.vsfire@1.4.1:h61hf1SYLs3VPHlSFosLlQ==
    - octref.vetur@0.22.2:KOvI2Xa9VX4Lga8ukQxS2A==
tasks:
  - command: npm install -g firebase-tools
  github:
  prebuilds:
    master: false
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addBadge: false